name: playing with cowsay

on: 
  push:
    branches:
      - main

jobs:
  install-cowsay:
    runs-on: ubuntu-latest
    steps:
      - name: step 1-install cowsay package
        run: sudo apt install cowsay
      
      - name: step 2-exeute cowsay
        run: cowsay -e @@ Hello >> cow.txt

      - name: step 3- test file exist
        run: grep -i "hello" cow.txt

      - name: step 4- read file
        run: cat cow.txt

      
      
