name: cowsay
on: push

jobs:
    Ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: install cowsay program
              run: sudo apt-get install cowsay -y
            
            - name: Execute cowsay CMD
              run: cowsay -f dragon "Run for cover, iam a Dragon....RAWR" >> dragon.txt

            - name: Test file exists
              run: grep -i "dragon" dragon.txt
            
            - name: Read File
              run: cat dragon.txt
            
            - name: checkout repo file
              run : ls

            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: dragon-file
                path: dragon.txt
            
    test_job2:
        runs-on: ubuntu-latest
        needs: Ascii_job
        steps:
            - name: download artifact
              uses: actions/download-artifact@v3
              with:
                name: dragon-file
            
            - name: Test file
              run: grep -i "dragon" dragon.txt


        