name: matrix-strategy
on:
  push:
    branches:
      - main

jobs:
  run-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16,17]
    steps:
      - name: print env info
        run: |
          echo "running on os ${{ matrix.os }}"
          echo " Node Version: ${{ matrix.node }}"
        
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      