name: my first work flow to run a bash script
on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: step 1- checkout to read the bash script on the runner
        uses: actions/checkout@v5

      - name: step 2- run the bash script
        run: |
          chmod +x script.sh
          ./script.sh